Project/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Project.Helper;
using Project.Models;
namespace Project.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        private MyModel db = new MyModel();
        [AuthorizationFilter]
        public ActionResult Index()
        {
            //var netsalary = db.Stores.Where(x => x.product_id == data.ID && x.IsArchive == true).Select(x => x.NetSalary).LastOrDefault();

            //var last = db.Stores.OrderByDescending(p => p.product_id).LastOrDefault().product_id;

            /*var count = db.Stores.GroupBy(n => n.product_id)
                        .Select(g => new { Count = g.Count() }).ToList();*/


            /*var count = db.Stores.GroupBy(n => n.product_id)
                        .Select(g => new {Count = g.Count() }).ToList();*/

            /*List<Storecount> CountList = new List<Storecount>();

            for (int i = 0; i < count.ToList().Count; i++)
            {
                CountList.Add(new Storecount { Count = count[i].Count });
            }*/
            var data = db.Store.Select(n => n.product_id).Count();
            ViewData["Message"] = data;

            var safe = db.Safe.Select(n => n.Safe_id).Count();
            ViewData["Safe"] = safe;

            var unSafe = db.Store.Select(n => n.product_id).Count();
            ViewData["unSafe"] = unSafe - safe;

            var proMo = db.Coupon.Select(n => n.Coupon_Id).Count();
            ViewData["proMo"] = proMo;

            var users = db.AspNetUsers.Select(n => n.Id).Count();
            ViewData["Users"] = users;

            return View();
        }


        public ActionResult Login()
        {
            return View();
        }

        public JsonResult checkLogin(string username, string password) 
        {
            var dataItem = db.AdminUser.Where(x => x.Username == username && x.Password == password).SingleOrDefault();
            bool isLogged = true;
            if (dataItem != null) 
            {
                //FormsAuthentication.SetAuthCookie(dataItem.Username, false);
                Session["Username"] = dataItem.Username;
                isLogged = true;

            }
            else 
            {
                isLogged = false;
            }
            return Json(isLogged, JsonRequestBehavior.AllowGet);
        }


    }
}

Project/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/Controllers/SafeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project;

namespace Project.Controllers
{
    public class SafeController : Controller
    {
        private MyModel db = new MyModel();

        // GET: Safe
        public ActionResult Index()
        {
            return View(db.Safe.ToList());
        }

        // GET: Safe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Safe safe = db.Safe.Find(id);
            if (safe == null)
            {
                return HttpNotFound();
            }
            return View(safe);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Controllers/SafesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project;
using Project.Helper;

namespace Project.Controllers
{
    public class SafesController : Controller
    {
        private MyModel db = new MyModel();

        // GET: Safes
        [AuthorizationFilter]
        public ActionResult Index()
        {
            return View(db.Safe.ToList());
        }

        // GET: Safes/Details/5
        [AuthorizationFilter]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Safe safe = db.Safe.Find(id);
            if (safe == null)
            {
                return HttpNotFound();
            }
            return View(safe);
        }

        // GET: Safes/Create
        [AuthorizationFilter]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Safes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Safe_id,Safe_name,Safe_img")] Safe safe)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    safe.Safe_img = fileName;
                }

                db.Safe.Add(safe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(safe);
        }

        // GET: Safes/Edit/5
        [AuthorizationFilter]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Safe safe = db.Safe.Find(id);
            if (safe == null)
            {
                return HttpNotFound();
            }
            return View(safe);
        }

        // POST: Safes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Safe_id,Safe_name,Safe_img")] Safe safe)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    safe.Safe_img = fileName;
                }

                db.Entry(safe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(safe);
        }

        // GET: Safes/Delete/5
        [AuthorizationFilter]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Safe safe = db.Safe.Find(id);
            if (safe == null)
            {
                return HttpNotFound();
            }
            return View(safe);
        }

        // POST: Safes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Safe safe = db.Safe.Find(id);
            db.Safe.Remove(safe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Views/Safes/Create.cshtml
@model Project.Safe

@*@{
        ViewBag.Title = "Create";
    }

    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Safe</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Safe_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Safe_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Safe_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Safe_img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Safe_img, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Safe_img, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Safe Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Create Safe Store</h1>
                                </div>
                                @using (Html.BeginForm("Create", "Safes", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()


                                    <div class="form-group">
                                        <p class="control-label col-md-2">ชื่อร้านที่ปลอดภัย</p>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Safe_name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Safe_name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">รูปใบรับรองฉีดวัคซีน</p>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Safe_img, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                                            @Html.ValidationMessageFor(model => model.Safe_img, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-outline-dark mt-auto " />
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Safes", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>

                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>
</html>

Project/Views/Safes/Delete.cshtml
@model Project.Safe

@*@{
        ViewBag.Title = "Delete";
    }

    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Safe</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Safe_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Safe_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Safe_img)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Safe_img)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Delete Safe Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Delete Safe Store</h1>
                                </div>

                                <form class="user">

                                    <div class="form-group">
                                        <b class="control-label col-md-2">ชื่อร้านที่ปลอดภัย</b>
                                        <div class="col-md-10">
                                            @Html.DisplayFor(model => model.Safe_name)
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <b class="control-label col-md-2">รูปใบรับรองฉีดวัคซีน</b>
                                        <div class="text-center">
                                            <img src=@Url.Content("~/Content/images/"+(Model.Safe_img)) style="width: 500px;height: auto" />
                                        </div>
                                    </div>


                                </form>

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-actions no-color">
                                        <input type="submit" value="Delete" class="btn btn-outline-dark mt-auto" />
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Safes", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>
                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>
</html>

Project/Views/Safes/Details.cshtml
@model Project.Safe

@*@{
        ViewBag.Title = "Details";
    }

    <h2>Details</h2>

    <div>
        <h4>Safe</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Safe_name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Safe_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Safe_img)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Safe_img)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Safe_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Details Safe Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Details Safe Store</h1>
                                </div>

                                <form class="user">

                                    <div class="form-group">
                                        <b class="control-label col-md-2">ชื่อร้านที่ปลอดภัย</b>
                                        <div class="col-md-10">
                                            @Html.DisplayFor(model => model.Safe_name)
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <b class="control-label col-md-2">รูปใบรับรองฉีดวัคซีน</b>
                                        <div class="text-center">
                                            <img src=@Url.Content("~/Content/images/"+(Model.Safe_img)) style="width: 500px; height: auto" />
                                        </div>
                                    </div>

                                    
                                </form>

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-actions no-color">
                                        @Html.ActionLink("Edit", "Edit", new { id = Model.Safe_id }, new { @class = "btn btn-outline-dark mt-auto " })
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Safes", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>
                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>
</html>

Project/Views/Safes/Edit.cshtml
@model Project.Safe

@*@{
        ViewBag.Title = "Edit";
    }

    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Safe</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Safe_id)

            <div class="form-group">
                @Html.LabelFor(model => model.Safe_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Safe_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Safe_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Safe_img, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Safe_img, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Safe_img, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Edit Safe Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Edit Safe Store</h1>
                                </div>
                                @using (Html.BeginForm("Edit", "Safes", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()

                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.Safe_id)

                                    <div class="form-group">
                                        <b class="control-label col-md-2">ชื่อร้านที่ปลอดภัย</b>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Safe_name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Safe_name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <b class="control-label col-md-2">รูปใบรับรองฉีดวัคซีน</b>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Safe_img, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                                            @Html.ValidationMessageFor(model => model.Safe_img, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <input type="submit" value="Save" class="btn btn-outline-dark mt-auto " />
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Safes", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>

                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>
</html>