Project/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project;

namespace Project.Controllers
{
    public class CouponController : Controller
    {
        private MyModel db = new MyModel();

        // GET: Coupon
        public ActionResult Index()
        {
            return View(db.Coupon.ToList());
        }
    
    }
}

Project/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/Controllers/PopularController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project;

namespace Project.Controllers
{
    public class PopularController : Controller
    {
        private MyModel db = new MyModel();

        // GET: Popular
        public ActionResult Index()
        {
            return View(db.Store.OrderByDescending(s => s.Review));
        }

        // GET: Popular/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Store.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // GET: Popular/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Popular/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,url,name,time,Review")] Store store)
        {
            if (ModelState.IsValid)
            {
                db.Store.Add(store);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(store);
        }

        // GET: Popular/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Store.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Popular/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,url,name,time,Review")] Store store)
        {
            if (ModelState.IsValid)
            {
                db.Entry(store).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(store);
        }

        // GET: Popular/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Store.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Popular/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Store store = db.Store.Find(id);
            db.Store.Remove(store);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Controllers/SafeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project;

namespace Project.Controllers
{
    public class SafeController : Controller
    {
        private MyModel db = new MyModel();

        // GET: Safe
        public ActionResult Index()
        {
            return View(db.Safe.ToList());
        }

        // GET: Safe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Safe safe = db.Safe.Find(id);
            if (safe == null)
            {
                return HttpNotFound();
            }
            return View(safe);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Views/Popular/Create.cshtml
@model Project.Store

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Store</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project/Views/Popular/Delete.cshtml
@model Project.Store

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Store</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Review)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Review)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/Views/Popular/Details.cshtml
@model Project.Store

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Review)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Review)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Views/Popular/Edit.cshtml
@model Project.Store

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Store</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.product_id)

        <div class="form-group">
            @Html.LabelFor(model => model.url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Review, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Project/Views/Popular/Index.cshtml
@model IEnumerable<Project.Store>
@using Microsoft.AspNet.Identity
@*@{
        ViewBag.Title = "Index";
    }

    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Review)
            </th>
            <th></th>
        </tr>

        <!-- @foreach (var item in Model) { -->
        @for (var i = 1; i <= 3; i++)
        {
            var indexItem = i - 1;
            <tr>
                <td>
                    @Model.ElementAt(indexItem).url
                </td>

                <td>
                    @Model.ElementAt(indexItem).Review
                </td>

            </tr>
        }

        </table>
*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="@Url.Content("~/Content/StylePop.css")" rel="stylesheet" type="text/css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Prompt&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <b><a class="navbar-brand" href="@Url.Action("Index", "Home")">SUT IN SIDE</a></b>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <!-- Menu Navigation -->
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Coupon")">โปรโมชั่น</a></li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Safe")">ร้านนี้ปลอดภัยชัวร์</a></li>
                    <li class="nav-item"><a class="nav-link active" href="@Url.Action("Index", "Popular")">ร้านอาหารยอดนิยม</a></li>

                </ul>

                <div class="d-flex">
                    <!-- Menu right -->
                    @Html.Partial("_LoginPartialEdit")
                </div>

            </div>
        </div>
    </nav>

    <!-- Header-->
    <br />
    <header class="bg-dark-edit py-5">

        <div class="container px-4 px-lg-5 my-5">
            <!--<div class="text-center text-black">-->
            @if (Request.IsAuthenticated)
            {
                <p><span class="display-4 fw-bolder">สวัสดีคุณ @User.Identity.GetUserName()</span></p>
                <!--<p><span class="lead fw-normal text-black-50 mb-0">คะแนนสะสมของคุณ : 0 point</span></p>-->
            }
            else
            {
                <p><span class="display-4 fw-bolder">สวัสดี ยินดีต้อนรับ</span></p>
            }

            <!-- Search -->
            


        </div>
        <!--</div>-->

    </header>

    <div class="container">

        <br />
        <p><span style="color: white" class="display-6 fw-bolder">ร้านอาหารยอดนิยม 3 อันดับ</span></p>
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
        </div>
        <br />

        <div class="row">
            @for (var i = 1; i <= 3; i++)
            {
                var indexItem = i - 1;

                <div class="col-md-4">
                    <div class="card user-card">
                        <div class="card-header">
                            @*<h5>Profile</h5>*@
                        </div>
                        <div class="card-block">

                            <div class="user-image">
                                <img src="@Url.Content("~/Content/images/" + (Model.ElementAt(indexItem).url))" class="img-radius" alt="User-Profile-Image">
                            </div>

                            <h6 class="f-w-600 m-t-25 m-b-10">@Model.ElementAt(indexItem).name</h6>
                            <p class="text-muted">Active | @Model.ElementAt(indexItem).time</p>
                            <hr>

                            <p class="text-muted m-t-15">Rating Stars</p>

                            <div class="d-flex justify-content-center small text-warning mb-2">
                                @for (var s = 1; s <= Model.ElementAt(indexItem).Review; s++)
                                {
                                    <div class="bi-star-fill"></div>
                                }
                            </div>

                            @Html.ActionLink("ดูเพิ่มเติม", "Select_Store", "Home", new { id = Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-outline-dark mt-auto" })

                        </div>
                    </div>
                </div>
            }

            </div>
    </div>


</body>
</html>

Project/Views/Popular/_LoginPartialEdit.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()

        <form class="flex">
            @*@Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })*@
            @*<a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>*@

            @Html.ActionLink("เปลี่ยนรหัสผ่าน", "ChangePassword", "Manage", null, new { @class = "btn btn-outline-dark mt-auto" })
            &nbsp;
            @Html.ActionLink("ออกจากระบบ", null, null, new { href = "javascript:document.getElementById('logoutForm').submit()", @class = "btn btn-outline-dark mt-auto" })

        </form>

    }
}

else
{
    <form class="flex">
        @Html.ActionLink("เข้าสู่ระบบ", "Login", "Account", null, new { @class = "btn btn-outline-dark mt-auto" })
        &nbsp;
        @Html.ActionLink("สมัคร", "Register", "Account", null, new { @class = "btn btn-outline-dark mt-auto" })
    </form>
}