Project/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Project.Helper;
using Project.Models;
namespace Project.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        private MyModel db = new MyModel();
        [AuthorizationFilter]
        public ActionResult Index()
        {
            //var netsalary = db.Stores.Where(x => x.product_id == data.ID && x.IsArchive == true).Select(x => x.NetSalary).LastOrDefault();

            //var last = db.Stores.OrderByDescending(p => p.product_id).LastOrDefault().product_id;

            /*var count = db.Stores.GroupBy(n => n.product_id)
                        .Select(g => new { Count = g.Count() }).ToList();*/


            /*var count = db.Stores.GroupBy(n => n.product_id)
                        .Select(g => new {Count = g.Count() }).ToList();*/

            /*List<Storecount> CountList = new List<Storecount>();

            for (int i = 0; i < count.ToList().Count; i++)
            {
                CountList.Add(new Storecount { Count = count[i].Count });
            }*/
            var data = db.Store.Select(n => n.product_id).Count();
            ViewData["Message"] = data;

            var safe = db.Safe.Select(n => n.Safe_id).Count();
            ViewData["Safe"] = safe;

            var unSafe = db.Store.Select(n => n.product_id).Count();
            ViewData["unSafe"] = unSafe - safe;

            var proMo = db.Coupon.Select(n => n.Coupon_Id).Count();
            ViewData["proMo"] = proMo;

            var users = db.AspNetUsers.Select(n => n.Id).Count();
            ViewData["Users"] = users;

            return View();
        }


        public ActionResult Login()
        {
            return View();
        }

        public JsonResult checkLogin(string username, string password) 
        {
            var dataItem = db.AdminUser.Where(x => x.Username == username && x.Password == password).SingleOrDefault();
            bool isLogged = true;
            if (dataItem != null) 
            {
                //FormsAuthentication.SetAuthCookie(dataItem.Username, false);
                Session["Username"] = dataItem.Username;
                isLogged = true;

            }
            else 
            {
                isLogged = false;
            }
            return Json(isLogged, JsonRequestBehavior.AllowGet);
        }


    }
}

Project/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Controllers
{
    public class DetailsController : Controller
    {
        // GET: Details
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/Controllers/StoresController.cs
using Project.Helper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Project
{
    public class StoresController : Controller
    {
        public MyModel db = new MyModel();

        // GET: Stores
        [AuthorizationFilter]
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.BrandSortParm = String.IsNullOrEmpty(sortOrder) ? "Brand_desc" : "";

            var store = from p in db.Store
                        select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                store = store.Where(p => p.name.ToUpper().Contains(searchString.ToUpper()));

            }

           /* switch (sortOrder)
            {
                case "Brand_desc":
                    phone = phone.OrderByDescending(p => p.brand);
                    break;
                default:
                    phone = phone.OrderBy(p => p.product_id);
                    break;
            }*/

            return View(store);
        }



        // GET: Stores/Details/5
        [AuthorizationFilter]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Store.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // GET: Stores/Create
        [AuthorizationFilter]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,url,name,time,Review")] Store store)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    store.url = fileName;
                }
                db.Store.Add(store);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(store);
        }

        // GET: Stores/Edit/5
        [AuthorizationFilter]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Store.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,url,name,time,Review")] Store store)
        {
            if (ModelState.IsValid)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    file.SaveAs(path);
                    store.url = fileName;
                }

                db.Entry(store).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(store);
        }

        // GET: Stores/Delete/5
        [AuthorizationFilter]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Store.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Store store = db.Store.Find(id);
            db.Store.Remove(store);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Views/Stores/Create.cshtml
@model Project.Store

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Create Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Create Store</h1>
                                </div>

                                @using (Html.BeginForm("Create", "Stores", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-group">
                                        <p class="control-label col-md-2">อัพโหลดรูปภาพ</p>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.url, new { htmlAttributes = new { @class = "form-control", type = "file" } })
                                            @Html.ValidationMessageFor(model => model.url, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">ชื่อร้าน</p>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">เวลา เปิด-ปิด</p>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ex. 06:00 AM - 19:00 PM" } })
                                            @*@Html.TextBoxFor(model => model.time, new { @id = "datetime", @class = "form-control datepicker" })*@
                                            @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">จำนวนดาวร้าน</p>
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Review, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Review, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-outline-dark mt-auto " />
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Stores", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>

                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script>
        // datetime
        $('#datetime').datetimepicker({
            format: 'hh:mm: a'
        });

        $('#datetime_end').datetimepicker({
            format: 'hh:mm: a'
        });
    </script>

</body>
</html>

Project/Views/Stores/Delete.cshtml
@model Project.Store

@*@{
            ViewBag.Title = "Delete";
            Layout = "~/Views/Shared/_Layout.cshtml";
        }



        <!--<h3>Are you sure you want to delete this?</h3>-->
    <div>
        <h2>Delete Store</h2>

        <hr />
        <dl class="dl-horizontal">
            <dt>
                รูปภาพ
            </dt>

            <dd>
                @Html.DisplayFor(model => model.url)
            </dd>

            <dt>
                ชื่อร้าน
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                เวลา เปิด-ปิด
            </dt>

            <dd>
                @Html.DisplayFor(model => model.time)
            </dd>

            <dt>
                จำนวนดาวร้าน
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Review)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-outline-dark mt-auto" />
                &nbsp;
                @Html.ActionLink("Back to List", "Index", null, null, new { @class = "btn btn-outline-dark mt-auto" })
            </div>
        }
    </div>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Delete Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Delete Store</h1>
                                </div>

                                <form class="user">

                                    <div class="form-group">
                                        <p class="control-label col-md-2">ชื่อรูปภาพ</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.url)</b>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">ชื่อร้าน</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.name)</b>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">เวลา เปิด-ปิด</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.time)</b>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">จำนวนดาวร้าน</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.Review)</b>
                                        </div>
                                    </div>

                                </form>

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-actions no-color">
                                        <input type="submit" value="Delete" class="btn btn-outline-dark mt-auto" />
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Stores", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>
                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>
</html>

Project/Views/Stores/Details.cshtml
@model Project.Store

@*@{
        ViewBag.Title = "Details";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }



    <div>
        <h2>Details Store</h2>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <!--@Html.DisplayNameFor(model => model.url)-->
                รูปภาพ
            </dt>

            <dd>
                @Html.DisplayFor(model => model.url)
            </dd>

            <dt>
                ชื่อร้าน
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                เวลา เปิด-ปิด
            </dt>

            <dd>
                @Html.DisplayFor(model => model.time)
            </dd>

            <dt>
                จำนวนดาวร้าน
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Review)
            </dd>

        </dl>
    </div>

    <!--<div>
        @Html.ActionLink("Edit", "Edit", "", null, new { id = Model.product_id, @class = "btn btn-outline-dark mt-auto" })
        &nbsp;
        @Html.ActionLink("Back to List", "Index", null, null, new { @class = "btn btn-outline-dark mt-auto" })

    </div>
    -->

    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
*@

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Details Store</title>
</head>

<body>
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <!-- <div class="col-lg-6 d-none d-lg-block bg-login-image"></div> -->

                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Details Store</h1>
                                </div>

                                <form class="user">

                                    <div class="form-group">
                                        <p class="control-label col-md-2">ชื่อรูปภาพ</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.url)</b>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">ชื่อร้าน</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.name)</b>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">เวลา เปิด-ปิด</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.time)</b>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <p class="control-label col-md-2">จำนวนดาวร้าน</p>
                                        <div class="col-md-10">
                                            <b>@Html.DisplayFor(model => model.Review)</b>
                                        </div>
                                    </div>

                                </form>

                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()
                                    <div class="form-actions no-color">
                                        @Html.ActionLink("Edit", "Edit", new { id = Model.product_id }, new { @class = "btn btn-outline-dark mt-auto " })
                                        &nbsp;
                                        @Html.ActionLink("Back to List", "Index", "Stores", null, new { @class = "btn btn-outline-dark mt-auto " })
                                    </div>
                                }

                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>
</html>

Project/Views/Stores/Index.cshtml
@model IEnumerable<Project.Store>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="@Url.Content("~/Content/Style1.css")" rel="stylesheet" type="text/css" />
    <link href="css/styles.css" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Prompt&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <b><a class="navbar-brand" href="@Url.Action("Index", "Home")">SUT IN SIDE</a></b>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link" aria-current="page" href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>

                </ul>

                <form class="d-flex">
                    @Html.ActionLink("เพิ่มร้านค้า", "Create", null, new { @class = "btn btn-success" })

                </form>
            </div>
        </div>
    </nav>

    <!-- Header-->
    <br />
    <header class="bg-dark-edit py-5">

        <div class="container px-4 px-lg-5 my-5">
            <!--<div class="text-center text-black">-->
            @if (Request.IsAuthenticated)
            {
                <p><span class="display-4 fw-bolder">สวัสดีคุณ @User.Identity.GetUserName()</span></p>
                <!--<p><span class="lead fw-normal text-black-50 mb-0">คะแนนสะสมของคุณ : 0 point</span></p>-->
            }
            else
            {
                <p><span class="display-4 fw-bolder">สวัสดี ยินดีต้อนรับ</span></p>
            }

            <!-- Search -->
            <div class="form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                @using ((Html.BeginForm()))
                {
                    <div class="input-group">
                        @Html.TextBox("searchString", null, new { @class = "form-control bg-light border-0 small", @placeholder = "ค้นหามื้ออาหารอร่อย ตรงนี้ !" })
                        <div class="input-group-append">
                            <button class="btn btn-danger" type="submit">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                }
            </div>


        </div>
        <!--</div>-->

    </header>

    <!--<div class="container">
        <div class="row">
            <div class="col text-right">
                @Html.ActionLink("เพิ่มร้านค้า", "Create", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
    <br />

    <div class="container">
        <div class="row">
            <div class="div-edit text-black-50-edit">
                @using ((Html.BeginForm()))
                {
                    @Html.TextBox("searchString", null, new { @placeholder = "ค้นหาชื่อร้านค้า" })
                    <input type="submit" class="btn btn-info" value="Search" />
                }
            </div>
        </div>
    </div>-->

    <section class="container">

        <br />
        <p><span style="color: white" class="display-6 fw-bolder">ร้านอาหาร</span></p>
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
        </div>

        <div class="container px-4 px-lg-5 mt-5">

            @for (var i = 1; i <= Model.ToList().Count(); i++)
            {
                var indexItem = i - 1;
                if (i == 1 || i % 4 == 1)
                {
                    @:<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    }
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Status New-->
                            <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">New!</div>
                            <!-- Product image -->
                            <img class="card-img-top" src="@Url.Content("~/Content/images/" + (Model.ElementAt(indexItem).url))" alt="..." />
                            <!-- <img class="img-responsive" style="max-width: 70%;" src=@Url.Content("~/Content/images/" + (Model.ElementAt(indexItem).url)) /> -->
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">@Model.ElementAt(indexItem).name</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        @for (var s = 1; s <= Model.ElementAt(indexItem).Review; s++)
                                        {
                                            <div class="bi-star-fill"></div>
                                        }
                                    </div>
                                    <!-- time -->
                                    @Model.ElementAt(indexItem).time
                                </div>
                            </div>


                            <!-- Product actions-->
                            <div class="pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    @*<a class="btn btn-outline-dark mt-auto" href="@Url.Action("Index", "Details")">ดูเพิ่มเติม</a>*@
                                    @Html.ActionLink("Details", "Details", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-outline-dark mt-auto" })
                                    @Html.ActionLink("Edit", "Edit", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-warning" })
                                    @Html.ActionLink("Delete", "Delete", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-danger" })
                                </div>
                            </div>
                            <br />

                            <!--<div class="caption">
                                <h3> @Model.ElementAt(indexItem).name </h3>
                                <h5> @Model.ElementAt(indexItem).time </h5>
                                <h5> @Model.ElementAt(indexItem).Review </h5>
                                @Html.ActionLink("Details", "Details", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-info" })
                                @Html.ActionLink("Edit", "Edit", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-warning" })
                                @Html.ActionLink("Delete", "Delete", new { id = @Model.ElementAt(indexItem).product_id }, new { @class = "btn btn-danger" })

                            </div>-->

                        </div>

                    </div>
                    if (i % 4 == 0)
                    {
                    @:</div>
                }
            }
        </div>
        @*แนะนำร้านอาหารเกิดใหม่*@

    </section>

    <!--<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Review)
            </th>
            <th></th>
        </tr>


    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src=@Url.Content("~/Content/images/"+(item.url)) style="width: 100px;height: auto" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Review)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.product_id }) |
                @Html.ActionLink("Details", "Details", new { id = item.product_id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.product_id })
            </td>
        </tr>
    }

    </table>-->
</body>
</html>